apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-app-dev
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devsecops-project

  source:
    repoURL:        https://github.com/abhisheksingh22se/devsecops-pipeline.git
    targetRevision: develop
    path:           k8s/overlays/dev

  destination:
    server:    https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration:    5s
        factor:      2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas