#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "🚀 Starting ArgoCD Bootstrap Process on EKS..."

# 1. Create the argocd namespace if it doesn't exist
echo "📦 Creating argocd namespace..."
kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

# 2. Install ArgoCD core components
echo "⚙️ Installing ArgoCD..."
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# 3. Wait for the ArgoCD server pod to be ready
echo "⏳ Waiting for ArgoCD pods to spin up (this may take a minute)..."
kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=300s

# 4. Expose the ArgoCD server locally via port-forwarding (runs in background)
# In production, you would place an Ingress/ALB in front of this.
echo "🔗 Port-forwarding ArgoCD UI to localhost:8080..."
kubectl port-forward svc/argocd-server -n argocd 8080:443 > /dev/null 2>&1 &
PF_PID=$!

# 5. Retrieve the default admin password (auto-generated by ArgoCD)
echo "🔑 Retrieving initial ArgoCD admin password..."
ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)

echo "------------------------------------------------------"
echo "✅ ArgoCD successfully installed!"
echo "🌐 UI URL: https://localhost:8080"
echo "👤 Username: admin"
echo "🔐 Password: $ARGOCD_PASSWORD"
echo "------------------------------------------------------"

# 6. Apply our custom GitOps boundaries and applications
echo "📂 Applying the DevSecOps AppProject and Application manifests..."
# Assuming you are running this from the root of your repo
kubectl apply -f argocd/project.yaml
kubectl apply -f argocd/app-dev.yaml

echo "🎉 Bootstrap complete! ArgoCD is now watching your Git repository."
echo "(Press Ctrl+C to stop the port-forwarding when you are done exploring the UI)"

kubectl apply -f argocd/monitoring.yaml

# Keep script running to maintain the port-forward
wait $PF_PID