apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      environment: dev

images:
  - name: devsecops-app
    # Replace with your actual ECR repository URI
    newName: devsecops-app
    newTag: local

patches:
  - target:
      kind: Deployment
      name: devsecops-app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: development